import { Setting } from "./enums";

export const settingsLayout : Record<Setting, [number, number, number]> = {
    [Setting.SHUFFLE_ITEMS]: [0, 6, 2],
    [Setting.OMIT_LOCATIONS]: [0, 4, 2],
    [Setting.INSERT_GS1_ITEMS]: [0, 3, 1],
    [Setting.SHOW_ITEM_SPRITES]: [0, 2, 1],
    [Setting.REMOVE_CLASS_PROGRESSION]: [0, 1, 1],
    [Setting.SHUFFLE_CLASS_STATS]: [0, 0, 1],

    [Setting.SHUFFLE_EQUIPMENT]: [1, 7, 1],
    [Setting.ADJUST_EQUIPMENT_COST]: [1, 6, 1],
    [Setting.ADJUST_EQUIPMENT_STATS]: [1, 5, 1],
    [Setting.SORT_EQUIPMENT]: [1, 4, 1],
    [Setting.SHUFFLE_UNLEASHES]: [1, 3, 1],
    [Setting.SHUFFLE_EQUIPMENT_EFFECT]: [1, 2, 1],
    [Setting.SHUFFLE_EQUIPMENT_CURSES]: [1, 1, 1],
    [Setting.ADJUST_PSYNERGY_POWER]: [1, 0, 1],

    [Setting.SHUFFLE_DJINN]: [2, 7, 1],
    [Setting.ADJUST_DJINN_STATS]: [2, 6, 1],
    [Setting.ADJUST_DJINN_POWER]: [2, 5, 1],
    [Setting.ADJUST_DJINN_RANGE]: [2, 4, 1],
    [Setting.SCALE_DJINN]: [2, 3, 1],
    [Setting.ADJUST_SUMMON_COST]: [2, 2, 1],
    [Setting.ADJUST_SUMMON_POWER]: [2, 1, 1],
    [Setting.SORT_SUMMONS]: [2, 0, 1],

    [Setting.CHANGE_CHARACTER_STATS]: [3, 6, 2],
    [Setting.CHANGE_CHARACTER_ELEMENT]: [3, 4, 2],
    [Setting.ADJUST_PSYNERGY_COST]: [3, 3, 1],
    [Setting.ADJUST_PSYNERGY_RANGE]: [3, 2, 1],
    [Setting.ADJUST_ENEMY_SKILL_POWER]: [3, 1, 1],
    [Setting.ADJUST_ENEMY_SKILL_RANGE]: [3, 0, 1],

    [Setting.SHUFFLE_CLASS_PSYNERGY]: [4, 5, 3],
    [Setting.CHANGE_CLASS_LEARN_LEVELS]: [4, 3, 2],
    [Setting.REMOVE_CUTSCENES]: [4, 2, 1],
    [Setting.REMOVE_SHOP_TICKETS]: [4, 1, 1],
    [Setting.FAST_SHIP]: [4, 0, 1],

    [Setting.SHIP_START]: [5, 6, 2],
    [Setting.SKIPS_RETREAT]: [5, 5, 1],
    [Setting.SKIPS_RETREAT_SAVEQUIT]: [5, 4, 1],
    [Setting.SKIPS_MAZE]: [5, 3, 1],
    [Setting.NO_BOSS_LOGIC]: [5, 2, 1],
    [Setting.FREE_AVOID]: [5, 1, 1],
    [Setting.FREE_RETREAT]: [5, 0, 1],

    [Setting.INCLUDE_SHOPS]: [6, 7, 1],
    [Setting.INSERT_DUMMY_ITEMS]: [6, 6, 1],
    [Setting.SKIPS_SANCWARP]: [6, 5, 1],
    [Setting.SHUFFLE_EQUIPMENT_ATTACK]: [6, 4, 1],
    [Setting.ENABLE_HINTS]: [6, 3, 1],
    [Setting.START_WITH_HEALING]: [6, 2, 1],
    [Setting.START_WITH_REVIVE]: [6, 1, 1],
    [Setting.START_WITH_REVEAL]: [6, 0, 1],

    [Setting.SCALE_EXP]: [7, 4, 4],
    [Setting.SCALE_COINS]: [7, 0, 4],

    [Setting.SHUFFLE_EQUIPMENT_DEFENSE]: [8, 7, 1],
    [Setting.STARTING_LEVEL]: [8, 0, 7],

    [Setting.CHANGE_ENEMY_ELEMENT]: [9, 6, 2],
    [Setting.SANCTUM_COST]: [9, 4, 2],
    [Setting.REMOVE_EQUIPMENT_CURSES]: [9, 3, 1],
    [Setting.ENABLE_AVOID_TOGGLE]: [9, 2, 1],
    [Setting.SKIPS_WIGGLECLIP]: [9, 1, 1],
    [Setting.SKIPS_MISSABLE]: [9, 0, 1],

    [Setting.ENABLE_HARD_MODE]: [10, 7, 1],
    [Setting.REDUCE_ENCOUNTER_RATE]: [10, 6, 1],
    [Setting.SPLIT_MAJOR_MINOR]: [10, 5, 1],
    [Setting.EASIER_BOSSES]: [10, 4, 1],
    [Setting.CHANGE_NAME_PUZZLES]: [10, 2, 2],
    [Setting.MANUAL_RETREAT_GLITCH]: [10, 1, 1],
    [Setting.SHIP_WINGS_START]: [10, 0, 1],

    [Setting.SHUFFLE_MUSIC]: [11, 7, 1],
    [Setting.BETTER_TELEPORT]: [11, 6, 1],
    [Setting.FORCE_BOSS_MAJORS]: [11, 5, 1],
    [Setting.FORCE_SUPERBOSS_MINORS]: [11, 4, 1],
    [Setting.ANEMOS_ACCESS]: [11, 2, 2],
    [Setting.SHUFFLE_CHARACTERS]: [11, 1, 1],
    [Setting.SKIPS_RETREAT_OOB]: [11, 0, 1],

    [Setting.SKIPS_SAND]: [12, 7, 1],
    [Setting.SKIPS_DEATH_STORAGE]: [12, 6, 1],
    [Setting.REMOVE_MIMICS]: [12, 5, 1],
    [Setting.SHORTCUT_MARS_LIGHTHOUSE]: [12, 4, 1],
    [Setting.SHORTCUT_MAGMA_ROCK]: [12, 3, 1],
    [Setting.SHUFFLE_ENTRANCES]: [12, 0, 3]
};