export enum Setting {
    SHUFFLE_ITEMS, 
    SPLIT_MAJOR_MINOR,
    OMIT_LOCATIONS, 
    FORCE_BOSS_MAJORS,
    FORCE_SUPERBOSS_MINORS,
    INCLUDE_SHOPS,
    NO_BOSS_LOGIC,
    SHIP_START,
    SHIP_WINGS_START,
    ANEMOS_ACCESS,

    BETTER_TELEPORT,
    CHANGE_NAME_PUZZLES,
    ENABLE_AVOID_TOGGLE,
    ENABLE_HARD_MODE,
    ENABLE_HINTS,
    FAST_SHIP,
    MANUAL_RETREAT_GLITCH,
    REDUCE_ENCOUNTER_RATE,
    REMOVE_CUTSCENES,
    REMOVE_MIMICS,
    REMOVE_SHOP_TICKETS,
    SHOW_ITEM_SPRITES,

    SHORTCUT_MAGMA_ROCK,
    SHORTCUT_MARS_LIGHTHOUSE,

    SCALE_COINS,
    SCALE_EXP,
    STARTING_LEVEL,
    SANCTUM_COST,

    SHUFFLE_CLASS_PSYNERGY,
    SHUFFLE_CLASS_STATS,
    CHANGE_CLASS_LEARN_LEVELS,
    REMOVE_CLASS_PROGRESSION, 

    SHUFFLE_CHARACTERS,
    CHANGE_CHARACTER_STATS,
    CHANGE_CHARACTER_ELEMENT,

    SHUFFLE_EQUIPMENT,
    SORT_EQUIPMENT,
    ADJUST_EQUIPMENT_COST,
    ADJUST_EQUIPMENT_STATS,
    SHUFFLE_EQUIPMENT_ATTACK,
    SHUFFLE_EQUIPMENT_DEFENSE,
    SHUFFLE_EQUIPMENT_EFFECT,
    SHUFFLE_EQUIPMENT_CURSES,
    REMOVE_EQUIPMENT_CURSES,
    SHUFFLE_UNLEASHES,
    INSERT_GS1_ITEMS, 
    INSERT_DUMMY_ITEMS,

    ADJUST_PSYNERGY_COST,
    ADJUST_PSYNERGY_POWER,
    ADJUST_PSYNERGY_RANGE,
    FREE_AVOID,
    FREE_RETREAT,
    START_WITH_HEALING,
    START_WITH_REVEAL,
    START_WITH_REVIVE,

    CHANGE_ENEMY_ELEMENT,
    ADJUST_ENEMY_SKILL_POWER,
    ADJUST_ENEMY_SKILL_RANGE,
    EASIER_BOSSES,

    SHUFFLE_DJINN,
    SCALE_DJINN,
    ADJUST_DJINN_POWER,
    ADJUST_DJINN_RANGE,
    ADJUST_DJINN_STATS,

    SORT_SUMMONS,
    ADJUST_SUMMON_COST,
    ADJUST_SUMMON_POWER,

    SHUFFLE_ENTRANCES,
    SHUFFLE_MUSIC,

    SKIPS_DEATH_STORAGE,
    SKIPS_MAZE,
    SKIPS_MISSABLE,
    SKIPS_RETREAT,
    SKIPS_RETREAT_SAVEQUIT,
    SKIPS_RETREAT_OOB,
    SKIPS_SANCWARP,
    SKIPS_SAND,
    // SKIPS_SHIPCLIP,
    SKIPS_WIGGLECLIP
}

export enum SettingAnemosAccess { VANILLA, RANDOM, OPEN };
export enum SettingClassPsynergy { NONE, BY_LINE, BY_GROUP, BY_ELEMENT, FULL, BY_GROUP_PREFER_ELEMENT };
export enum SettingGenericTernary { NONE, PARTIAL, FULL };
export enum SettingNamePuzzles { VANILLA, FIXED, RANDOM };
export enum SettingOmitLocations { NONE, OMIT_ANEMOS, OMIT_SUPERBOSSES, OMIT_BOTH };
export enum SettingShuffleItems { NONE, KEY_ITEMS, CHESTS, ALL };
export enum SettingShuffleEntrances { NONE, ACCESS, INTERNAL, ACCESS_INTERNAL, FULL };
export enum SettingShipStart { VANILLA, DOOR_OPEN, UNLOCKED };
export enum SettingSanctumCost { VANILLA, REDUCED, FIXED, INCREASED };